### ISSUE TITLE
재홍님 안녕하세요. 

### ISSUE THREAD

**Issue by alisol** [pyrasis/dockerbook#1]
도커 책 정말 고맙습니다.
재홍님의 지식을 널리 알리기 위해 어려운 출판을 해주셔서 많은 도움이 된다고 생각합니다.

다름이 아니란.
처음 도커책이 출판된지 버써 5년이 되었는데요. 

개정판을 내주실 수 있을까 해서요. 

새로운 이야기들이 분명 있을 거라고 생각합니다.

많은 것이 변하지는 않았지만 시간이 지난 만큼 개정판이 나온다면

다시 도커 책을 기다리는 분들에게 큰 도움이 될 거라고 생각합니다. 

꼭 개정판 내주시면 좋겠습니다.

**Comment by pyrasis** [comment]
안녕하세요. 이재홍입니다.

예전에 출판사와 이야기 한 적이 있습니다만, 현실적인 문제 등으로 인해 쉽지 않다는 이야기를 들었습니다.

다양한 방면으로 고민해보겠습니다.

의견주셔서 감사합니다.
